title: "Security Now!"
subtitle: "Open DNS (ODNS)"
author: 
#email: your-email@secnow.net
description: >- # this means to ignore newlines until "baseurl:"
  Multiline desc starts here.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://odns.secnow.net" # the base hostname & protocol for your site

navbar_list:
- name: Home
  link: /
- name: DoUDP Measurements
  link: /data
- name: DoTCP Measurements
  link: /tcp-scans
- name: CoNEXT'21 Artifacts
  link: https://github.com/ilabrg/artifacts-conext21-dns-fwd
- name: Paper
  link: /assets/static/nksw-tfuco-21.pdf
- name: Contact
  link: /contact

sass:
  compressed: true
